language: ruby
rvm:
  - 2.0.0-p598
notifications:
  slack: dbc-copperheads:M2bM6eOSd4Ksy4cKacLEpp4h
services: mongodb

before_script:
  - be rake db:drop
  - be rake db:purge
  - foreman start
  - be rake db:create
  - be rake db:migrate

