language: ruby
rvm:
  - 2.0.0-p598
notifications:
  slack: dbc-copperheads:M2bM6eOSd4Ksy4cKacLEpp4h
services: mongodb

before_script:
  - bundle exec foreman start
  - bundle exec rake db:create
  - bundle exec rake db:migrate

addons:
  postgresql: 9.3
